### ISSUE TITLE
TypeError: 'dict' object is not callable

### ISSUE THREAD

**Issue by csarn** [menschel/mdfminer#1]
I just tried to use mdfminer, and there is a bug in 
[mdf.py line 384](https://github.com/menschel/mdfminer/blob/master/mdfminer/mdf.py#L384)
Where you should use square brackets instead of parentheses.

**Comment by menschel** [comment]
Thx,
I never had a mdf file with a working extentions block, so this bug slipped through.

**Comment by menschel** [comment]
Fixed and updated on PiPy, Thx again.
